### ISSUE TITLE
To CLI or not to CLI?

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-info#1]
I built this tool to try and help answer my own questions about the state of a service or some tasks on a cluster. The ECS UI in the console is pretty good, but sometimes falls short or involves a ridiculous amount of clicking.

I wanted to answer questions like:
- how many tasks are running concurrently on the same host as this one?
- how are my service  tasks distributed across hosts?
- how are my watchbot tasks distributed across hosts?
- how many watchbot tasks that have recently failed, and what was the reason for the failure?

To answer these questions involves quite a few ECS API requests, so this lib basically just does them all -- you tell it what cluster to look at, and it describes everything about that cluster. Surprisingly, all those API requests really don't take terribly long, and once you've made them you can build [an object that lets you navigate through the relationships between tasks, services, and instances](https://github.com/mapbox/ecs-info/blob/21911cf92a79cc6398d5436a540c30576b847abc/readme.md#cluster-description).

So all that's the preamble to the question: should this lib have a CLI that helps you answer some set of specific questions? Or should it just do the API requests to return the object? That would allow something like ecs-watchbot to provide a CLI that depends on this lib, but provides querying and formatting appropriate for watchbot apps.

Any thoughts from the ecs adopters? @emilymcafee @yhahn @tcql @rodowi @l-r @aarthykc

**Comment by aarthykc** [comment]
> how many watchbot tasks that have recently failed, and what was the reason for the failure?
> 👍  

This is awesome! :tada: 

I remember while trying to set up ecs-watchbot, I had to keep going to `ECS -> Cluster -> task -> events` to see what happened to the task. Whether the service was running (i.e reached a steady state) or it was unable to start the service and threw this error: 

```
Was unable to place a task because no container instance met all of its requirements. Reason: No Container Instances were found in your cluster. For more information, see the Troubleshooting section.

```

It might be helpful to have a CLI tool, that would give the status of the event? and the link to troubleshoot if it failed to place the task (?)

**Comment by l-r** [comment]
> should this lib have a CLI that helps you answer some set of specific questions? Or should it just do the API requests to return the object?

Can we have it both ways? So a generic lib to wrap the API requests and return the object, so that specific stacks can build on top of – and at the same time, a slim "general ECS info" tool (also built on top), for everything else?

If that's spreading ourselves too thin, I would lean towards "answering a set of specific questions", my only worry is that AWS changes/breaks all the time.

> The ECS UI in the console is pretty good, but sometimes falls short or involves a ridiculous amount of clicking.

Yep, that and I'm often terrified that a UI bug will cause me to nuke a stack by mistake. Everything that keeps up away from the UI is 👍

**Comment by defvol** [comment]
To be honest, at this moment I'm not sure about what questions to ask to ECS. I 👍  for a CLI that answers specific questions following whatever we define as best practices.

**Comment by rclark** [comment]
As I've played around with this, I've found myself adjusting the CLI tool each time I have some question about a service that I want answered. I'm all for a "general ECS info" tool like @l-r suggests, but I am not completely sure what it would do. Maybe we need a little brainstorming on what the CLI tools interface would be?

**Comment by rclark** [comment]
Some starter ideas for CLI commands:
- list services running on a cluster
- list tasks running under any single service
- list watchbot services running on a cluster
- list tasks running as part of any watchbot service
- get details of any single instance: resources available, tasks running
- tell me the total free memory/cpu available on a cluster
- tell me the max memory/cpu available on any single EC2 in the cluster

**Comment by defvol** [comment]
is it possible to get the SNS Subject and Messages of running tasks?
that would be useful to monitor stacks on reduce mode, i.e. where tasks might perform differently depending on the piece of code they are running...

**Comment by rclark** [comment]
Yes -- check out https://github.com/mapbox/ecs-info/blob/master/lib/Task.js#L88

**Comment by tcql** [comment]
> Some starter ideas for CLI commands:
- in general, 'describe' a cluster - when starting a new ecs based stack, we need to know the cluster ARN, but it'd also be handy to see general information in one command, like 
  - how many instances
  - what kind of instances
  - what current reservation %s are (to know if this cluster will work for what we're deploying or if needs to be scaled)
- this is maybe crazy, but for commands that are listing running tasks, could we implement a tail mode, so you could run it like `top` to monitor execution of a service across the cluster?

**Comment by rclark** [comment]
The instance info suggestions can be implemented immediately. The tail suggestion is a little more complex -- I think that it might end up being up to the details of the application's logging implementation.

For example, a watchbot stack has a single CloudWatch LogGroup. All the containers will write logs there, and we can read the logs from that group with something like https://github.com/mapbox/cwlogs. I'd like to implement `--tail` kind of functionality there, but I haven't figured out yet how to do it with the API CloudWatch gives us.

**Comment by rclark** [comment]
Started putting together an overview command:

```
》ecs-info overview processing-production

  arn:aws:ecs:us-east-1:123456789012:cluster/ecs-cluster-processing-production-Cluster-ABCDEFG
  --------------------------------------------------------------------------------------------------
  EC2s                          : 3                  
  Memory (available/registered) : 626782/627294      
  CPU (available/registered)    : 98304/98304        
  Most free memory              : 208970 (i-1234)
  Most free CPU                 : 32768 (i-1234) 
  Total running tasks           : 3                  


  Instance Type  us-east-1a  us-east-1d  us-east-1e  total
  -------------  ----------  ----------  ----------  -----
  r3.8xlarge     1           1           1           3    


  Service                                Running Tasks
  -------------------------------------  -------------
  ecs-conex-production-Watchbot          1            
  cloud-roomba-production-CloudRoomba    1            
```

**Comment by rclark** [comment]
ECS peeps: update your ecs-info, `npm link`, and try out 

`ecs-info overview <cluster name>`: to see what kind of action is happening and what's available on a cluster.

`ecs-info drilldown <cluster name>`: to look for specific tasks associated with some service or watchbot system. I think this could be really useful for figuring out why watchbot worker tasks failed to start.

Let me know if you have further suggestions or requests.

**Comment by l-r** [comment]
Looking great. A few superficial ideas after trying it a bit:
- could `ecs-info overview` return services in alphabetical order?
- how about a `-h` to get human-readable version of memory
- some alignment is a bit off in both `overview` and `drilldown`

**Comment by defvol** [comment]
This is super useful

```
✗ ecs-info drilldown ecs-cluster
? Select a service or other task starter ...
? Select a task STOPPED at 2016-10-14T14:20:51.860Z
  status          : STOPPED
  uptime          : 0m30.40s
  started by      : ...
  stopped because : Essential container in task exited
```

Is it possible to add memory usage per job? Uptime and memory are the two things I need to inspect at the moment.

**Comment by rclark** [comment]
Memory usage per job is not accessible via the ECS api, and also not likely available from the docker api after the container has stopped. [Some info here](https://github.com/mapbox/ecs-watchbot/issues/43#issuecomment-244550312) about getting metrics on running containers.

**Comment by rclark** [comment]
Going to close here, I've just been kind of arbitrarily adding cli commands.
